config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'projects#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show new create destroy update]
  resources :organisations, only: %i[index new create destroy]
  resources :sites, only: %i[show new create destroy] do
    get '/checks', to: 'sites#checks'
  end
  resources :projects, only: %i[index new create destroy]
  resources :slack_settings, only: %i[show new create update edit destroy]
  get '/probes', to: 'probes#index'
  post '/probes', to: 'probes#create'
  get '/probes/health/:id', to: 'probes#health'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :rememberable, :trackable, :validatable
  include Gravtastic
  gravtastic

  validates :name, presence: true

  validates :terms_and_conditions, acceptance: { accept: 'yes' }
  belongs_to :organisation, optional: true

  after_create :make_admin

  def role
    return 'Platform Admin' if platform_admin
    return 'Admin' if admin
    'User'
  end

  private

  # Make this user a organisation admin unless they have been invited
  def make_admin
    update(admin: true) unless invitation_token
  end
end

app/controllers/users/invitations_controller.rb
module Users
  class InvitationsController < Devise::InvitationsController
    before_action :configure_permitted_parameters, if: :devise_controller?
    def invite_params
      super.merge(organisation_id: current_user.organisation.id)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:invite, keys: [:name])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  skip_before_action :authenticate_user!, only: %i[new create]

  # GET /users
  # GET /users.json
  def index
    @users = policy_scope(User)
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    authorize :user, :new?
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(users_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_user_session_path, notice: 'User was successfully created, please login.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(users_update_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json {}
      else
        format.html { render :show }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def users_params
    params.require(:user).permit(:name, :email, :password, :terms_and_conditions)
  end

  def users_update_params
    params.require(:user).permit(:name, :email, :organisation_id, :admin, :platform_admin)
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, class: 'label' %>
    <div class="control">
      <%= f.text_field :email, autofocus: true, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :password, class: 'label' %>
    <div class="control">
      <%= f.password_field :password, class: 'input' %>
    </div>
  </div>

    <div class="field">
      <%= f.label 'Confirm Password', class: 'label' %>
      <div class="control">
        <%= f.password_field :password_confirmation, class: 'input' %>
      </div>
    </div>

    <div class="control is-grouped">
      <p class="control">
        <%= f.submit "Next", class: 'button is-primary' %>
      </p>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Users</h3>
    <div class="card-options">
      <%= link_to '<i class="fe fe-plus"></i> Invite User'.html_safe, new_user_invitation_path, class: 'btn btn-primary', style: 'color: white' %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table card-table table-striped table-vcenter">
      <thead>
        <tr>
          <th colspan="2">User</th>
          <th>Status</th>
          <th>Last Login</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td class="w-1">
            <span class="avatar">
              <%= image_tag user.gravatar_url, class: 'avatar' %>
            </span>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <% if user.invited_to_sign_up? %>
                Invite Pending
            <% elsif user == current_user %>
              <%= user.role %>
            <% else %>
              <div class="form-group" style="width: 200px; margin: 10px -10px;">
                <select class="custom-select role" data-id="<%= user.id %>">
                  <option>User</option>
                  <option <%= 'selected' if user.admin? && !user.platform_admin? %>>Admin</option>
                  <% if current_user.platform_admin? %>
                    <option <%= 'selected' if user.platform_admin? %>>Platform Admin</option>
                  <% end %>
                </select>
              </div>
            <% end %>
          </td>
          <td class="text-nowrap"><%= user.updated_at %></td>
          <td class="w-1">
            <%= link_to '<i class="fe fe-trash"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } unless user == current_user %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
    $( ".role" ).change(function(element) {
        var id = $(element.currentTarget).data("id");
        var role = $(element.currentTarget ).val();
        var data = {
            admin: role == 'Admin',
            platform_admin: role == 'Platform Admin',
        };
        $.ajax({
            url : '/users/' + id + '.json',
            data : JSON.stringify({user: data}),
            type : 'PATCH',
            contentType : 'application/json',
            dataType: 'json',
            success: function () {
                window.location.reload();
            }
        });
    });
</script>

app/views/users/new.html.erb
<div class="page">
  <div class="page-single">
    <div class="container">
      <div class="row">
        <div class="col col-login mx-auto">
          <%= form_for(@user, html: {class: 'card'}) do |f| %>
            <div class="card-body p-6">
              <div class="card-title">Create new account</div>
              <div class="form-group">
                <label class="form-label">Name</label>
                <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Enter name' %>
                <div class="invalid-feedback" style="display: block">
                  <%= @user.errors[:name].join(', ') if @user.errors[:name].size > 0 %>
                </div>
              </div>
              <div class="form-group">
                <label class="form-label">Email address</label>
                <%= f.text_field :email, class: 'form-control', placeholder: 'Enter email' %>
                <div class="invalid-feedback" style="display: block">
                  <%= @user.errors[:email].join(', ') if @user.errors[:email].size > 0 %>
                </div>
              </div>
              <div class="form-group">
                <label class="form-label">Password</label>
                <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
                <div class="invalid-feedback" style="display: block">
                  <%= @user.errors[:password].join(', ') if @user.errors[:password].size > 0 %>
                </div>
              </div>
              <div class="form-group">
                <label class="custom-control custom-checkbox">
                  <input id="user_terms_and_conditions" type="checkbox" class="custom-control-input" name="user[terms_and_conditions]" value="yes"/>
                  <span class="custom-control-label">Agree to the <a href="#" data-toggle="modal" data-target="#terms_and_conditions">Terms</a></span>
                  <div class="invalid-feedback" style="display: block">
                    <%= @user.errors[:terms_and_conditions].join(', ') if @user.errors[:terms_and_conditions].size > 0 %>
                  </div>
                </label>
              </div>
              <div class="form-footer">
                <button type="submit" class="btn btn-primary btn-block">Create</button>
              </div>
            </div>
          <% end %>
          <div class="text-center text-muted">
            Already have account? <%= link_to 'Sign in', new_user_session_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="terms_and_conditions" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Licence</h5>
        <button type="button" class="close" data-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        This is free and unencumbered software released into the public domain.
        <br><br>
        Anyone is free to copy, modify, publish, use, compile, sell, or
        distribute this software, either in source code form or as a compiled
        binary, for any purpose, commercial or non-commercial, and by any
        means.
        <br><br>
        In jurisdictions that recognize copyright laws, the author or authors
        of this software dedicate any and all copyright interest in the
        software to the public domain. We make this dedication for the benefit
        of the public at large and to the detriment of our heirs and
        successors. We intend this dedication to be an overt act of
        relinquishment in perpetuity of all present and future rights to this
        software under copyright law.
        <br><br>
        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
        IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
        OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
        ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
        OTHER DEALINGS IN THE SOFTWARE.
        <br><br>
        For more information, please refer to http://unlicense.org
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="title">Editing User</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email, class: 'label' %>
      <div class="control">
        <%= f.text_field :email, autofocus: true, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= f.label :organisation_id, class: 'label' %>
      <div class="control">
        <div class="select">
          <%= f.collection_select(:organisation_id, Organisation.all, :id, :name) %>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <label class="checkbox">
          <%= f.check_box :admin %>
          Administrator
        </label>
      </div>
    </div>

    <div class="control is-grouped">
      <p class="control">
        <%= f.submit "Update", class: 'button is-primary' %>
      </p>
    </div>
<% end %>